<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="CheckOpiFormat-20171122132258" tests="7" time="0.000">
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_labels_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_THEN_it_ends_in_a_colon" time="0.000">
		<error message="global name 'get_labels_that_do_not_end_in_colons' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 315, in test_GIVEN_a_label_THEN_it_ends_in_a_colon
    errors = get_labels_that_do_not_end_in_colons()
NameError: global name 'get_labels_that_do_not_end_in_colons' is not defined
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000">
		<error message="On line 121, text 'Position', colour was not correct.
On line 1431, text 'Advanced', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 297, in test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background
    self._assert_colour_correct("background_color", "groupingContainer", ["ISIS_OPI_Background"])
  File "check_opi_format.py", line 294, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 121, text 'Position', colour was not correct.
On line 1431, text 'Advanced', colour was not correct.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
